### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by PangXitong** [JingYiJun/MOSS_backend#10]
您好，运行```git clone https://github.com/JingYiJun/MOSS_backend.git ```克隆仓库后
如何运行服务端以在[http://localhost:8000/docs](http://localhost:8000/docs)上运行

**Comment by JingYiJun** [comment]
此后端不包含对话推断模型，仅包含登录、注册、数据存储功能；如果一定要配置，请按照config/config.go配置环境变量，以及配置kong网关环境用于jwt的签发和校验。
